name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Get
      run: go get github.com/hashicorp/hcl/hclsimple
    - name: Build
      run: go build .
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
