name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Build
      run: go build .
      
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}:${{ github.head_ref }}
